var a1=3;
document.write(++a1);
document.write("<br>");
var a2=20;
document.write(++a2);
document.write("<br>");
document.write("<br>");
var a3=10;
document.write(++a3);
document.write("<br>");
document.write(++a3);
document.write("<br>");
document.write("<br>");
var a4=5;
document.write(a4++);
document.write("<br>");
document.write(a4++);
document.write("<br>");
document.write(a4++);
document.write("<br>");
document.write("<br>");
var a5=15;
document.write(--a5);
document.write("<br>");
document.write(--a5);
document.write("<br>");
document.write("<br>");
var a6=20;
document.write(a6--);
document.write("<br>");
document.write(a6--);
document.write("<br>");
document.write(a6--);
document.write("<br>");
document.write("<br>");
var a7=2;
document.write(a7--);
document.write(a7--);
document.write(a7--);
document.write("<br>");
document.write("<br>");
var a8=2;
document.write(++a8);
document.write(a8++);
document.write("<br>");
document.write(a8);
document.write("<br>");
document.write("<br>");
var a9=1;
document.write(a9++);
document.write("<br>");
document.write(a9++);
document.write("<br>");
document.write(a9);
