document.write(3*3);
document.write(4/2);
document.write("<br>");
var a=5+10;
document.write(a);
document.write("<br>");
var b=55-28;
document.write(b);
document.write("<br>");
var c=10*2;
document.write(c);
document.write("<br>");
var d="3+6";
document.write(d);
document.write("<br>");
var e="2+3";
var f="4-1";
document.write(e);
document.write("<br>");
document.write(f);
document.write("<br>");
var g=5*5;
var h="5*5";
document.write(h+"="+g);
document.write("<br>");
var abc1=10%3;
document.write(abc1);
document.write("<br>");
var abc2=5%2;
document.write("5÷2の余りは"+abc2);
document.write("<br>");
var abc3="8%2";
document.write(abc3);
document.write("<br>");
var abc4=3%2;
var abc5=1;
document.write(abc4+"="+abc5);